import { Student, ClusterSummary } from "./types";


const generateCommitHistory = (base: number) => {
  const data = [];
  for (let i = 29; i >= 0; i--) {
    const d = new Date();
    d.setDate(d.getDate() - i);
    data.push({
      date: d.toISOString().split("T")[0],
      count: Math.max(0, Math.floor(base + Math.random() * 6 - 2)),
    });
  }
  return data;
};

const generateSubmissions = (base: number) => {
  const data = [];
  for (let i = 29; i >= 0; i--) {
    const d = new Date();
    d.setDate(d.getDate() - i);
    data.push({
      date: d.toISOString().split("T")[0],
      count: Math.max(0, Math.floor(base + Math.random() * 4 - 1)),
    });
  }
  return data;
};

export const students: Student[] = [
  {
    id: "1", name: "Mayank Sharma", email: "mayank@college.edu", avatarUrl: "",
    githubUsername: "mayank12sharma", leetcodeUsername: "mayank-05-old", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 20,
    leetcode: { totalSolved: 90, easy: 46, medium: 19, hard: 2, streak: 6, ranking: 126868, recentSubmissions: generateSubmissions(0) },
    github: { totalCommits: 169, totalRepos: 2, totalPRs: 6, totalStars: 0, languages: [{ name: "Java", percentage: 59 }, { name: "HTML", percentage: 41 }], commitHistory: generateCommitHistory(0) },
  },
  {
    id: "2", name: "Anuj Kumar", email: "anuj@college.edu", avatarUrl: "",
    githubUsername: "AnujKumar1204", leetcodeUsername: "anuj1210", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 81,
    leetcode: { totalSolved: 483, easy: 141, medium: 229, hard: 74, streak: 33, ranking: 17223, recentSubmissions: generateSubmissions(3) },
    github: { totalCommits: 1159, totalRepos: 23, totalPRs: 30, totalStars: 137, languages: [{ name: "C", percentage: 41 }, { name: "C++", percentage: 44 }, { name: "TypeScript", percentage: 15 }], commitHistory: generateCommitHistory(6) },
  },
  {
    id: "3", name: "Prerita Saini", email: "prerita@college.edu", avatarUrl: "",
    githubUsername: "preritasaini1", leetcodeUsername: "Prerita_1", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 52,
    leetcode: { totalSolved: 247, easy: 76, medium: 105, hard: 37, streak: 13, ranking: 79565, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 385, totalRepos: 8, totalPRs: 22, totalStars: 22, languages: [{ name: "HTML", percentage: 66 }, { name: "C++", percentage: 34 }], commitHistory: generateCommitHistory(3) },
  },
  {
    id: "4", name: "Parth Garg", email: "parth@college.edu", avatarUrl: "",
    githubUsername: "Parthgarg27", leetcodeUsername: "parth_garg77", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 48,
    leetcode: { totalSolved: 112, easy: 39, medium: 50, hard: 1, streak: 1, ranking: 159742, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 104, totalRepos: 2, totalPRs: 3, totalStars: 0, languages: [{ name: "SQL", percentage: 46 }, { name: "C", percentage: 31 }, { name: "TypeScript", percentage: 23 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "5", name: "Sarvagya Saxena", email: "sarvagya@college.edu", avatarUrl: "",
    githubUsername: "SarvagyaSaxena101", leetcodeUsername: "sarvagyasaxena2006", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 83,
    leetcode: { totalSolved: 479, easy: 159, medium: 227, hard: 44, streak: 39, ranking: 15607, recentSubmissions: generateSubmissions(4) },
    github: { totalCommits: 1246, totalRepos: 22, totalPRs: 40, totalStars: 99, languages: [{ name: "SQL", percentage: 66 }, { name: "C", percentage: 34 }], commitHistory: generateCommitHistory(5) },
  },
  {
    id: "6", name: "Rudraksh Mahajan", email: "rudraksh@college.edu", avatarUrl: "",
    githubUsername: "raiden9420", leetcodeUsername: "Rudrax9420", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 21,
    leetcode: { totalSolved: 78, easy: 19, medium: 25, hard: 6, streak: 3, ranking: 117350, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 84, totalRepos: 6, totalPRs: 5, totalStars: 1, languages: [{ name: "TypeScript", percentage: 42 }, { name: "C++", percentage: 43 }, { name: "Kotlin", percentage: 15 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "7", name: "Uday Chauhan", email: "uday@college.edu", avatarUrl: "",
    githubUsername: "Udaychauhan1724", leetcodeUsername: "Uday_Chauhan04", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 58,
    leetcode: { totalSolved: 299, easy: 97, medium: 134, hard: 22, streak: 13, ranking: 54373, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 320, totalRepos: 16, totalPRs: 23, totalStars: 7, languages: [{ name: "SQL", percentage: 65 }, { name: "TypeScript", percentage: 35 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "8", name: "Ansham Maurya", email: "ansham@college.edu", avatarUrl: "",
    githubUsername: "ANSHAM1", leetcodeUsername: "Ansham_Maurya", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 39,
    leetcode: { totalSolved: 36, easy: 64, medium: 29, hard: 9, streak: 4, ranking: 238704, recentSubmissions: generateSubmissions(0) },
    github: { totalCommits: 94, totalRepos: 6, totalPRs: 0, totalStars: 5, languages: [{ name: "JavaScript", percentage: 40 }, { name: "C++", percentage: 34 }, { name: "Go", percentage: 26 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "9", name: "Aavya", email: "aavya@college.edu", avatarUrl: "",
    githubUsername: "aavya1234", leetcodeUsername: "Aavya1234", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 83,
    leetcode: { totalSolved: 428, easy: 148, medium: 162, hard: 72, streak: 49, ranking: 13486, recentSubmissions: generateSubmissions(3) },
    github: { totalCommits: 1005, totalRepos: 21, totalPRs: 39, totalStars: 87, languages: [{ name: "CSS", percentage: 55 }, { name: "C", percentage: 45 }], commitHistory: generateCommitHistory(6) },
  },
  {
    id: "10", name: "Ashish Kumar", email: "ashish@college.edu", avatarUrl: "",
    githubUsername: "ashishkumar03440", leetcodeUsername: "ashsih03440", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 86,
    leetcode: { totalSolved: 378, easy: 115, medium: 147, hard: 55, streak: 48, ranking: 28591, recentSubmissions: generateSubmissions(3) },
    github: { totalCommits: 780, totalRepos: 17, totalPRs: 61, totalStars: 144, languages: [{ name: "TypeScript", percentage: 55 }, { name: "SQL", percentage: 45 }], commitHistory: generateCommitHistory(6) },
  },
  {
    id: "11", name: "Shiv Kumar", email: "shiv@college.edu", avatarUrl: "",
    githubUsername: "optimus-shiv", leetcodeUsername: "Shivkumar117", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 25,
    leetcode: { totalSolved: 87, easy: 69, medium: 18, hard: 8, streak: 7, ranking: 152730, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 109, totalRepos: 5, totalPRs: 5, totalStars: 3, languages: [{ name: "Java", percentage: 50 }, { name: "JavaScript", percentage: 50 }], commitHistory: generateCommitHistory(0) },
  },
  {
    id: "12", name: "Yashraj Mishra", email: "yashraj@college.edu", avatarUrl: "",
    githubUsername: "yashrajmishra40", leetcodeUsername: "yashraj_2315800095", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 92,
    leetcode: { totalSolved: 358, easy: 137, medium: 168, hard: 40, streak: 22, ranking: 11929, recentSubmissions: generateSubmissions(4) },
    github: { totalCommits: 934, totalRepos: 17, totalPRs: 32, totalStars: 150, languages: [{ name: "C++", percentage: 55 }, { name: "SQL", percentage: 45 }], commitHistory: generateCommitHistory(4) },
  },
  {
    id: "13", name: "Pankhuri Agrawal", email: "pankhuri@college.edu", avatarUrl: "",
    githubUsername: "PankhuriAgrawal607", leetcodeUsername: "pankhuriagrawal_607", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 79,
    leetcode: { totalSolved: 485, easy: 159, medium: 252, hard: 76, streak: 38, ranking: 25488, recentSubmissions: generateSubmissions(3) },
    github: { totalCommits: 948, totalRepos: 30, totalPRs: 56, totalStars: 64, languages: [{ name: "C", percentage: 49 }, { name: "Go", percentage: 21 }, { name: "SQL", percentage: 30 }], commitHistory: generateCommitHistory(4) },
  },
  {
    id: "14", name: "Harshit Chaudhary", email: "harshit@college.edu", avatarUrl: "",
    githubUsername: "harshitchaudha", leetcodeUsername: "harshitchaudhry109", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 40,
    leetcode: { totalSolved: 45, easy: 22, medium: 30, hard: 5, streak: 7, ranking: 128644, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 93, totalRepos: 3, totalPRs: 3, totalStars: 4, languages: [{ name: "TypeScript", percentage: 42 }, { name: "C++", percentage: 47 }, { name: "Rust", percentage: 11 }], commitHistory: generateCommitHistory(0) },
  },
  {
    id: "15", name: "Somesh Rajput", email: "somesh@college.edu", avatarUrl: "",
    githubUsername: "somesh78", leetcodeUsername: "rajputsomesh78", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 34,
    leetcode: { totalSolved: 45, easy: 21, medium: 46, hard: 8, streak: 7, ranking: 103868, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 53, totalRepos: 8, totalPRs: 3, totalStars: 1, languages: [{ name: "Java", percentage: 40 }, { name: "Go", percentage: 32 }, { name: "Python", percentage: 28 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "16", name: "Sneha Chaudhary", email: "sneha@college.edu", avatarUrl: "",
    githubUsername: "SNEHA-CHAUDHARY03", leetcodeUsername: "sneha_chaudhary", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 87,
    leetcode: { totalSolved: 367, easy: 159, medium: 240, hard: 69, streak: 29, ranking: 23861, recentSubmissions: generateSubmissions(4) },
    github: { totalCommits: 1269, totalRepos: 30, totalPRs: 39, totalStars: 64, languages: [{ name: "CSS", percentage: 41 }, { name: "HTML", percentage: 59 }], commitHistory: generateCommitHistory(4) },
  },
  {
    id: "17", name: "Vaishvik Sharma", email: "vaishvik@college.edu", avatarUrl: "",
    githubUsername: "vaishviksharma", leetcodeUsername: "vaishviksharma7860", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 21,
    leetcode: { totalSolved: 32, easy: 76, medium: 37, hard: 8, streak: 2, ranking: 114910, recentSubmissions: generateSubmissions(0) },
    github: { totalCommits: 160, totalRepos: 2, totalPRs: 2, totalStars: 0, languages: [{ name: "JavaScript", percentage: 53 }, { name: "CSS", percentage: 21 }, { name: "Java", percentage: 26 }], commitHistory: generateCommitHistory(0) },
  },
  {
    id: "18", name: "Siddhartha Khandelwal", email: "siddhartha@college.edu", avatarUrl: "",
    githubUsername: "Siddharthakhandelwal", leetcodeUsername: "siddharthakhandelwal9", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 33,
    leetcode: { totalSolved: 100, easy: 48, medium: 18, hard: 10, streak: 6, ranking: 182361, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 91, totalRepos: 4, totalPRs: 6, totalStars: 1, languages: [{ name: "JavaScript", percentage: 54 }, { name: "Python", percentage: 23 }, { name: "Rust", percentage: 23 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "19", name: "Isha Vashishtha", email: "isha@college.edu", avatarUrl: "",
    githubUsername: "Isha-Vashishtha", leetcodeUsername: "Isha_vashishtha", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 81,
    leetcode: { totalSolved: 429, easy: 116, medium: 156, hard: 62, streak: 48, ranking: 12254, recentSubmissions: generateSubmissions(4) },
    github: { totalCommits: 950, totalRepos: 26, totalPRs: 48, totalStars: 60, languages: [{ name: "CSS", percentage: 35 }, { name: "SQL", percentage: 55 }, { name: "HTML", percentage: 10 }], commitHistory: generateCommitHistory(6) },
  },
  {
    id: "20", name: "Akshat Somani", email: "akshat@college.edu", avatarUrl: "",
    githubUsername: "AkshatGLA", leetcodeUsername: "akshatsachinsomani", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 71,
    leetcode: { totalSolved: 176, easy: 78, medium: 93, hard: 13, streak: 9, ranking: 76256, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 329, totalRepos: 12, totalPRs: 17, totalStars: 24, languages: [{ name: "SQL", percentage: 67 }, { name: "Kotlin", percentage: 33 }], commitHistory: generateCommitHistory(3) },
  },
  {
    id: "21", name: "Aaditya Ranjan Moitra", email: "aaditya@college.edu", avatarUrl: "",
    githubUsername: "AadityaSukhoi", leetcodeUsername: "CodingAvgeek", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 65,
    leetcode: { totalSolved: 214, easy: 73, medium: 71, hard: 30, streak: 14, ranking: 58132, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 272, totalRepos: 8, totalPRs: 18, totalStars: 29, languages: [{ name: "Kotlin", percentage: 57 }, { name: "Rust", percentage: 43 }], commitHistory: generateCommitHistory(3) },
  },
  {
    id: "22", name: "Prashant", email: "prashant@college.edu", avatarUrl: "",
    githubUsername: "prashantsorout001", leetcodeUsername: "Prashant_sorout01", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 37,
    leetcode: { totalSolved: 22, easy: 29, medium: 9, hard: 2, streak: 5, ranking: 109444, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 124, totalRepos: 6, totalPRs: 8, totalStars: 1, languages: [{ name: "C++", percentage: 68 }, { name: "C", percentage: 32 }], commitHistory: generateCommitHistory(0) },
  },
  {
    id: "23", name: "Ishita Agarwal", email: "ishita@college.edu", avatarUrl: "",
    githubUsername: "ishitagarwal10", leetcodeUsername: "Ishita_Agarwal10", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 47,
    leetcode: { totalSolved: 30, easy: 60, medium: 18, hard: 10, streak: 2, ranking: 126946, recentSubmissions: generateSubmissions(0) },
    github: { totalCommits: 120, totalRepos: 8, totalPRs: 8, totalStars: 3, languages: [{ name: "TypeScript", percentage: 40 }, { name: "Go", percentage: 60 }], commitHistory: generateCommitHistory(0) },
  },
  {
    id: "24", name: "Aeshna Varshney", email: "aeshna@college.edu", avatarUrl: "",
    githubUsername: "aeshnavarshney25", leetcodeUsername: "aeshnavarshney", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 85,
    leetcode: { totalSolved: 500, easy: 159, medium: 192, hard: 55, streak: 28, ranking: 15216, recentSubmissions: generateSubmissions(4) },
    github: { totalCommits: 810, totalRepos: 27, totalPRs: 32, totalStars: 149, languages: [{ name: "Rust", percentage: 49 }, { name: "C", percentage: 51 }], commitHistory: generateCommitHistory(4) },
  },
  {
    id: "25", name: "Lav Saraswat", email: "lav@college.edu", avatarUrl: "",
    githubUsername: "LavSaraswat", leetcodeUsername: "Lav_Saraswat", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 47,
    leetcode: { totalSolved: 78, easy: 43, medium: 6, hard: 10, streak: 2, ranking: 204455, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 114, totalRepos: 4, totalPRs: 1, totalStars: 2, languages: [{ name: "Python", percentage: 40 }, { name: "JavaScript", percentage: 38 }, { name: "C++", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "26", name: "Rahul Gupta", email: "rahul@college.edu", avatarUrl: "",
    githubUsername: "Rahul20004", leetcodeUsername: "rg8490832", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 28,
    leetcode: { totalSolved: 29, easy: 28, medium: 43, hard: 6, streak: 3, ranking: 182228, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 141, totalRepos: 6, totalPRs: 8, totalStars: 0, languages: [{ name: "Python", percentage: 51 }, { name: "Go", percentage: 37 }, { name: "Kotlin", percentage: 12 }], commitHistory: generateCommitHistory(0) },
  },
  {
    id: "27", name: "Pawan Agrawal", email: "pawan@college.edu", avatarUrl: "",
    githubUsername: "Pawan-Agrawall", leetcodeUsername: "Pavan1456", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 43,
    leetcode: { totalSolved: 70, easy: 61, medium: 32, hard: 1, streak: 6, ranking: 186559, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 189, totalRepos: 4, totalPRs: 1, totalStars: 5, languages: [{ name: "C", percentage: 52 }, { name: "Go", percentage: 24 }, { name: "C++", percentage: 24 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "28", name: "Jayendra Singh", email: "jayendra@college.edu", avatarUrl: "",
    githubUsername: "jayendrasingh22", leetcodeUsername: "JayendraSingh122", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 87,
    leetcode: { totalSolved: 473, easy: 147, medium: 255, hard: 51, streak: 39, ranking: 28648, recentSubmissions: generateSubmissions(3) },
    github: { totalCommits: 1008, totalRepos: 27, totalPRs: 65, totalStars: 146, languages: [{ name: "Java", percentage: 54 }, { name: "Go", percentage: 30 }, { name: "CSS", percentage: 16 }], commitHistory: generateCommitHistory(5) },
  },
  {
    id: "29", name: "Shivam Rajput", email: "shivam@college.edu", avatarUrl: "",
    githubUsername: "sh1vamRajput", leetcodeUsername: "shivamrajput0537", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 64,
    leetcode: { totalSolved: 204, easy: 102, medium: 120, hard: 35, streak: 20, ranking: 51120, recentSubmissions: generateSubmissions(3) },
    github: { totalCommits: 587, totalRepos: 9, totalPRs: 17, totalStars: 21, languages: [{ name: "SQL", percentage: 47 }, { name: "C++", percentage: 53 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "30", name: "Archi Agrawal", email: "archi@college.edu", avatarUrl: "",
    githubUsername: "04archi", leetcodeUsername: "04archi", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 24,
    leetcode: { totalSolved: 26, easy: 20, medium: 20, hard: 7, streak: 5, ranking: 119091, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 146, totalRepos: 5, totalPRs: 3, totalStars: 5, languages: [{ name: "Java", percentage: 38 }, { name: "TypeScript", percentage: 47 }, { name: "Python", percentage: 15 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "31", name: "Nishi Srivastava", email: "nishi@college.edu", avatarUrl: "",
    githubUsername: "NISHISRIVASTAVA123", leetcodeUsername: "NISHI_20", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 91,
    leetcode: { totalSolved: 418, easy: 103, medium: 211, hard: 55, streak: 49, ranking: 13976, recentSubmissions: generateSubmissions(5) },
    github: { totalCommits: 1167, totalRepos: 19, totalPRs: 59, totalStars: 125, languages: [{ name: "Rust", percentage: 48 }, { name: "CSS", percentage: 37 }, { name: "HTML", percentage: 15 }], commitHistory: generateCommitHistory(6) },
  },
  {
    id: "32", name: "Raj Shwet Gautam", email: "raj@college.edu", avatarUrl: "",
    githubUsername: "raj11gautam", leetcodeUsername: "Raj112128", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 55,
    leetcode: { totalSolved: 271, easy: 98, medium: 93, hard: 34, streak: 11, ranking: 58173, recentSubmissions: generateSubmissions(3) },
    github: { totalCommits: 516, totalRepos: 15, totalPRs: 28, totalStars: 12, languages: [{ name: "Kotlin", percentage: 47 }, { name: "C++", percentage: 53 }], commitHistory: generateCommitHistory(3) },
  },
  {
    id: "33", name: "Bhavya Tandon", email: "bhavya@college.edu", avatarUrl: "",
    githubUsername: "bhavyatan", leetcodeUsername: "bhavya__133", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 60,
    leetcode: { totalSolved: 288, easy: 75, medium: 77, hard: 14, streak: 11, ranking: 65102, recentSubmissions: generateSubmissions(3) },
    github: { totalCommits: 328, totalRepos: 11, totalPRs: 10, totalStars: 18, languages: [{ name: "Go", percentage: 48 }, { name: "Python", percentage: 32 }, { name: "Java", percentage: 20 }], commitHistory: generateCommitHistory(3) },
  },
  {
    id: "34", name: "Nimit Goyal", email: "nimit@college.edu", avatarUrl: "",
    githubUsername: "nimix26", leetcodeUsername: "_Nimit26", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 38,
    leetcode: { totalSolved: 25, easy: 63, medium: 35, hard: 0, streak: 3, ranking: 178279, recentSubmissions: generateSubmissions(0) },
    github: { totalCommits: 129, totalRepos: 8, totalPRs: 6, totalStars: 4, languages: [{ name: "C++", percentage: 55 }, { name: "Go", percentage: 45 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "35", name: "Abhijith Jicks", email: "abhijith@college.edu", avatarUrl: "",
    githubUsername: "abhijithjicks", leetcodeUsername: "abhijithjicks", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 85,
    leetcode: { totalSolved: 471, easy: 143, medium: 242, hard: 65, streak: 43, ranking: 15408, recentSubmissions: generateSubmissions(3) },
    github: { totalCommits: 1178, totalRepos: 19, totalPRs: 69, totalStars: 108, languages: [{ name: "JavaScript", percentage: 53 }, { name: "SQL", percentage: 47 }], commitHistory: generateCommitHistory(5) },
  },
  {
    id: "36", name: "Nitin Kumar", email: "nitin@college.edu", avatarUrl: "",
    githubUsername: "Nitin99sogarwal", leetcodeUsername: "nitin514", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 89,
    leetcode: { totalSolved: 346, easy: 103, medium: 173, hard: 64, streak: 30, ranking: 16935, recentSubmissions: generateSubmissions(4) },
    github: { totalCommits: 1165, totalRepos: 25, totalPRs: 51, totalStars: 137, languages: [{ name: "C++", percentage: 35 }, { name: "JavaScript", percentage: 54 }, { name: "Rust", percentage: 11 }], commitHistory: generateCommitHistory(5) },
  },
  {
    id: "37", name: "Jyotsana Bhardwaj", email: "jyotsana@college.edu", avatarUrl: "",
    githubUsername: "jyotsana15", leetcodeUsername: "Jyotsana_Bhardwaj", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 86,
    leetcode: { totalSolved: 357, easy: 141, medium: 148, hard: 42, streak: 44, ranking: 11016, recentSubmissions: generateSubmissions(3) },
    github: { totalCommits: 953, totalRepos: 21, totalPRs: 31, totalStars: 119, languages: [{ name: "Rust", percentage: 43 }, { name: "SQL", percentage: 57 }], commitHistory: generateCommitHistory(4) },
  },
  {
    id: "38", name: "Aryan Tiwari", email: "aryan@college.edu", avatarUrl: "",
    githubUsername: "Aryantiwarib", leetcodeUsername: "Aryan_cs23", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 56,
    leetcode: { totalSolved: 269, easy: 114, medium: 92, hard: 34, streak: 13, ranking: 50996, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 560, totalRepos: 17, totalPRs: 30, totalStars: 8, languages: [{ name: "CSS", percentage: 69 }, { name: "Python", percentage: 31 }], commitHistory: generateCommitHistory(3) },
  },
  {
    id: "39", name: "Parth Sharma", email: "parth@college.edu", avatarUrl: "",
    githubUsername: "parthsharma-7", leetcodeUsername: "parthsharma7", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 71,
    leetcode: { totalSolved: 246, easy: 95, medium: 85, hard: 12, streak: 17, ranking: 55915, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 302, totalRepos: 12, totalPRs: 29, totalStars: 24, languages: [{ name: "HTML", percentage: 37 }, { name: "Go", percentage: 52 }, { name: "C", percentage: 11 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "40", name: "Mukti Mishra", email: "mukti@college.edu", avatarUrl: "",
    githubUsername: "MuktiMishra", leetcodeUsername: "MuktiMishra", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 20,
    leetcode: { totalSolved: 127, easy: 77, medium: 11, hard: 6, streak: 3, ranking: 220517, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 69, totalRepos: 5, totalPRs: 2, totalStars: 5, languages: [{ name: "Go", percentage: 45 }, { name: "CSS", percentage: 27 }, { name: "C++", percentage: 28 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "41", name: "Ayush Mittal", email: "ayush@college.edu", avatarUrl: "",
    githubUsername: "Ayush-AI-ux", leetcodeUsername: "Ayush_Mittal_637", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 22,
    leetcode: { totalSolved: 91, easy: 72, medium: 20, hard: 7, streak: 5, ranking: 199349, recentSubmissions: generateSubmissions(0) },
    github: { totalCommits: 116, totalRepos: 2, totalPRs: 7, totalStars: 2, languages: [{ name: "C", percentage: 50 }, { name: "C++", percentage: 50 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "42", name: "Arjun Singh Rajput", email: "arjun@college.edu", avatarUrl: "",
    githubUsername: "ArjunRajputGLA", leetcodeUsername: "CodeXI", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 69,
    leetcode: { totalSolved: 220, easy: 105, medium: 61, hard: 26, streak: 11, ranking: 45610, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 373, totalRepos: 14, totalPRs: 23, totalStars: 22, languages: [{ name: "Rust", percentage: 44 }, { name: "Python", percentage: 27 }, { name: "JavaScript", percentage: 29 }], commitHistory: generateCommitHistory(3) },
  },
  {
    id: "43", name: "Garvit Kedia", email: "garvit@college.edu", avatarUrl: "",
    githubUsername: "Garvit-kedia", leetcodeUsername: "garvitkedia2", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 57,
    leetcode: { totalSolved: 228, easy: 112, medium: 134, hard: 21, streak: 15, ranking: 76272, recentSubmissions: generateSubmissions(3) },
    github: { totalCommits: 521, totalRepos: 13, totalPRs: 21, totalStars: 28, languages: [{ name: "C++", percentage: 42 }, { name: "Kotlin", percentage: 23 }, { name: "SQL", percentage: 35 }], commitHistory: generateCommitHistory(3) },
  },
  {
    id: "44", name: "Akshansh Maurya", email: "akshansh@college.edu", avatarUrl: "",
    githubUsername: "akshanshmaurya", leetcodeUsername: "Akshansh_maurya", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 30,
    leetcode: { totalSolved: 50, easy: 38, medium: 17, hard: 3, streak: 6, ranking: 226929, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 100, totalRepos: 7, totalPRs: 8, totalStars: 4, languages: [{ name: "C++", percentage: 51 }, { name: "Java", percentage: 49 }], commitHistory: generateCommitHistory(0) },
  },
  {
    id: "45", name: "Harshit Rathi", email: "harshit@college.edu", avatarUrl: "",
    githubUsername: "Rathi2005", leetcodeUsername: "Harshit_Rathi", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 75,
    leetcode: { totalSolved: 481, easy: 134, medium: 156, hard: 57, streak: 21, ranking: 11786, recentSubmissions: generateSubmissions(4) },
    github: { totalCommits: 1266, totalRepos: 24, totalPRs: 38, totalStars: 121, languages: [{ name: "CSS", percentage: 55 }, { name: "C++", percentage: 45 }], commitHistory: generateCommitHistory(4) },
  },
  {
    id: "46", name: "Harsh Gupta", email: "harsh@college.edu", avatarUrl: "",
    githubUsername: "HarshGupta-283104", leetcodeUsername: "PH76O5nMoT", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 60,
    leetcode: { totalSolved: 197, easy: 73, medium: 92, hard: 40, streak: 15, ranking: 47476, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 283, totalRepos: 14, totalPRs: 23, totalStars: 7, languages: [{ name: "CSS", percentage: 42 }, { name: "C++", percentage: 58 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "47", name: "Parmeet Singh", email: "parmeet@college.edu", avatarUrl: "",
    githubUsername: "parmeetsingh1313n", leetcodeUsername: "parmeetsingh1313n", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 23,
    leetcode: { totalSolved: 126, easy: 43, medium: 38, hard: 6, streak: 4, ranking: 216056, recentSubmissions: generateSubmissions(0) },
    github: { totalCommits: 106, totalRepos: 8, totalPRs: 6, totalStars: 2, languages: [{ name: "SQL", percentage: 48 }, { name: "Java", percentage: 52 }], commitHistory: generateCommitHistory(0) },
  },
  {
    id: "48", name: "Gaurav Chaudhary", email: "gaurav@college.edu", avatarUrl: "",
    githubUsername: "Gaurav-Chaudhary04", leetcodeUsername: "chaudharygaurav147", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 25,
    leetcode: { totalSolved: 81, easy: 37, medium: 40, hard: 1, streak: 2, ranking: 100701, recentSubmissions: generateSubmissions(0) },
    github: { totalCommits: 134, totalRepos: 5, totalPRs: 7, totalStars: 2, languages: [{ name: "Kotlin", percentage: 37 }, { name: "C++", percentage: 34 }, { name: "Rust", percentage: 29 }], commitHistory: generateCommitHistory(0) },
  },
  {
    id: "49", name: "Tejas Mishra", email: "tejas@college.edu", avatarUrl: "",
    githubUsername: "tejas-stack", leetcodeUsername: "tejasmishra04", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 45,
    leetcode: { totalSolved: 70, easy: 69, medium: 12, hard: 8, streak: 2, ranking: 139056, recentSubmissions: generateSubmissions(0) },
    github: { totalCommits: 98, totalRepos: 8, totalPRs: 2, totalStars: 0, languages: [{ name: "CSS", percentage: 49 }, { name: "Kotlin", percentage: 23 }, { name: "C++", percentage: 28 }], commitHistory: generateCommitHistory(0) },
  },
  {
    id: "50", name: "Madhav Sharma", email: "madhav@college.edu", avatarUrl: "",
    githubUsername: "Madhav7851", leetcodeUsername: "6LjGnB0t8X", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 59,
    leetcode: { totalSolved: 253, easy: 87, medium: 124, hard: 27, streak: 15, ranking: 68688, recentSubmissions: generateSubmissions(3) },
    github: { totalCommits: 291, totalRepos: 17, totalPRs: 9, totalStars: 33, languages: [{ name: "Python", percentage: 53 }, { name: "JavaScript", percentage: 20 }, { name: "Java", percentage: 27 }], commitHistory: generateCommitHistory(3) },
  },
  {
    id: "51", name: "Keshav Agrawal", email: "keshav@college.edu", avatarUrl: "",
    githubUsername: "keshav-agrawal595", leetcodeUsername: "keshav-agrawal1", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 41,
    leetcode: { totalSolved: 88, easy: 20, medium: 16, hard: 7, streak: 5, ranking: 215927, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 101, totalRepos: 3, totalPRs: 6, totalStars: 5, languages: [{ name: "C", percentage: 45 }, { name: "Go", percentage: 41 }, { name: "Kotlin", percentage: 14 }], commitHistory: generateCommitHistory(0) },
  },
  {
    id: "52", name: "Rishabh Jain", email: "rishabh@college.edu", avatarUrl: "",
    githubUsername: "rishabh-jain26", leetcodeUsername: "rishabh_jain_26", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 80,
    leetcode: { totalSolved: 384, easy: 126, medium: 228, hard: 71, streak: 29, ranking: 23122, recentSubmissions: generateSubmissions(4) },
    github: { totalCommits: 1263, totalRepos: 16, totalPRs: 59, totalStars: 51, languages: [{ name: "JavaScript", percentage: 35 }, { name: "Go", percentage: 54 }, { name: "HTML", percentage: 11 }], commitHistory: generateCommitHistory(5) },
  },
  {
    id: "53", name: "Sneha Agrawal", email: "sneha@college.edu", avatarUrl: "",
    githubUsername: "Sneha15sep", leetcodeUsername: "snehaagrawal_cs23", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 51,
    leetcode: { totalSolved: 198, easy: 103, medium: 106, hard: 29, streak: 20, ranking: 72669, recentSubmissions: generateSubmissions(3) },
    github: { totalCommits: 570, totalRepos: 15, totalPRs: 9, totalStars: 11, languages: [{ name: "Rust", percentage: 35 }, { name: "Kotlin", percentage: 35 }, { name: "JavaScript", percentage: 30 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "54", name: "Om Lakshkar", email: "om@college.edu", avatarUrl: "",
    githubUsername: "Omlakshkar07", leetcodeUsername: "omlakshkar07", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 29,
    leetcode: { totalSolved: 23, easy: 67, medium: 10, hard: 3, streak: 7, ranking: 129743, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 148, totalRepos: 2, totalPRs: 2, totalStars: 3, languages: [{ name: "Rust", percentage: 49 }, { name: "Kotlin", percentage: 37 }, { name: "Java", percentage: 14 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "55", name: "Anamika Lodhi", email: "anamika@college.edu", avatarUrl: "",
    githubUsername: "anamikalodhi01", leetcodeUsername: "anamikalodhi01", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 81,
    leetcode: { totalSolved: 453, easy: 132, medium: 235, hard: 48, streak: 47, ranking: 12287, recentSubmissions: generateSubmissions(5) },
    github: { totalCommits: 982, totalRepos: 28, totalPRs: 51, totalStars: 140, languages: [{ name: "C++", percentage: 66 }, { name: "Kotlin", percentage: 34 }], commitHistory: generateCommitHistory(5) },
  },
  {
    id: "56", name: "Karunendra Nath Dwivedy", email: "karunendra@college.edu", avatarUrl: "",
    githubUsername: "Karunendra27", leetcodeUsername: "Karunendra_Dwivedy", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 71,
    leetcode: { totalSolved: 275, easy: 79, medium: 117, hard: 27, streak: 15, ranking: 62618, recentSubmissions: generateSubmissions(3) },
    github: { totalCommits: 420, totalRepos: 16, totalPRs: 25, totalStars: 17, languages: [{ name: "Kotlin", percentage: 58 }, { name: "Java", percentage: 42 }], commitHistory: generateCommitHistory(3) },
  },
  {
    id: "57", name: "Nikhil Singh", email: "nikhil@college.edu", avatarUrl: "",
    githubUsername: "Fauzdarnikhil", leetcodeUsername: "nikhilsingh1477", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 74,
    leetcode: { totalSolved: 255, easy: 72, medium: 100, hard: 33, streak: 15, ranking: 64984, recentSubmissions: generateSubmissions(3) },
    github: { totalCommits: 447, totalRepos: 18, totalPRs: 28, totalStars: 9, languages: [{ name: "HTML", percentage: 50 }, { name: "CSS", percentage: 50 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "58", name: "Ronit Singh", email: "ronit@college.edu", avatarUrl: "",
    githubUsername: "RonitSingh01", leetcodeUsername: "ronitsingh12", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 47,
    leetcode: { totalSolved: 132, easy: 27, medium: 38, hard: 7, streak: 1, ranking: 137789, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 134, totalRepos: 8, totalPRs: 2, totalStars: 0, languages: [{ name: "CSS", percentage: 45 }, { name: "Go", percentage: 41 }, { name: "JavaScript", percentage: 14 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "59", name: "Utkarsh Maheshwari", email: "utkarsh@college.edu", avatarUrl: "",
    githubUsername: "utkarsh9916", leetcodeUsername: "utkarsh", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 32,
    leetcode: { totalSolved: 101, easy: 77, medium: 39, hard: 0, streak: 5, ranking: 117936, recentSubmissions: generateSubmissions(0) },
    github: { totalCommits: 90, totalRepos: 7, totalPRs: 4, totalStars: 1, languages: [{ name: "SQL", percentage: 54 }, { name: "JavaScript", percentage: 46 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "60", name: "Chintakayala Venkata Abhishek", email: "chintakayala@college.edu", avatarUrl: "",
    githubUsername: "VenkataAbhishekTech", leetcodeUsername: "Chintakayala_Venkata_Abhishek", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 84,
    leetcode: { totalSolved: 307, easy: 102, medium: 181, hard: 43, streak: 29, ranking: 21746, recentSubmissions: generateSubmissions(5) },
    github: { totalCommits: 1083, totalRepos: 28, totalPRs: 39, totalStars: 71, languages: [{ name: "TypeScript", percentage: 42 }, { name: "Kotlin", percentage: 58 }], commitHistory: generateCommitHistory(5) },
  },
  {
    id: "61", name: "Krishna Bansal", email: "krishna@college.edu", avatarUrl: "",
    githubUsername: "KrishnaBansal63", leetcodeUsername: "krishnabansal0592005", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 32,
    leetcode: { totalSolved: 81, easy: 78, medium: 42, hard: 2, streak: 2, ranking: 220887, recentSubmissions: generateSubmissions(0) },
    github: { totalCommits: 193, totalRepos: 4, totalPRs: 7, totalStars: 2, languages: [{ name: "SQL", percentage: 37 }, { name: "HTML", percentage: 48 }, { name: "TypeScript", percentage: 15 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "62", name: "Aditya Pratap Singh", email: "aditya@college.edu", avatarUrl: "",
    githubUsername: "Adityaa-Pratap-Singh", leetcodeUsername: "its_aditya243", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 38,
    leetcode: { totalSolved: 96, easy: 69, medium: 49, hard: 4, streak: 4, ranking: 179199, recentSubmissions: generateSubmissions(0) },
    github: { totalCommits: 80, totalRepos: 5, totalPRs: 7, totalStars: 0, languages: [{ name: "CSS", percentage: 35 }, { name: "C++", percentage: 45 }, { name: "SQL", percentage: 20 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "63", name: "Om Makhija", email: "om@college.edu", avatarUrl: "",
    githubUsername: "OmMakhija", leetcodeUsername: "om_makhija", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 68,
    leetcode: { totalSolved: 162, easy: 108, medium: 123, hard: 36, streak: 12, ranking: 55081, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 560, totalRepos: 13, totalPRs: 15, totalStars: 25, languages: [{ name: "SQL", percentage: 68 }, { name: "JavaScript", percentage: 32 }], commitHistory: generateCommitHistory(3) },
  },
  {
    id: "64", name: "Aditya Pachaury", email: "aditya@college.edu", avatarUrl: "",
    githubUsername: "adityapachaury", leetcodeUsername: "aditya_pachaury", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 21,
    leetcode: { totalSolved: 99, easy: 71, medium: 7, hard: 9, streak: 3, ranking: 134448, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 53, totalRepos: 4, totalPRs: 5, totalStars: 5, languages: [{ name: "TypeScript", percentage: 68 }, { name: "HTML", percentage: 32 }], commitHistory: generateCommitHistory(0) },
  },
  {
    id: "65", name: "Srikant Choubey", email: "srikant@college.edu", avatarUrl: "",
    githubUsername: "Srikant-03", leetcodeUsername: "Srikant_04", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 36,
    leetcode: { totalSolved: 148, easy: 49, medium: 15, hard: 4, streak: 7, ranking: 226313, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 105, totalRepos: 7, totalPRs: 5, totalStars: 0, languages: [{ name: "Java", percentage: 63 }, { name: "SQL", percentage: 37 }], commitHistory: generateCommitHistory(0) },
  },
  {
    id: "66", name: "Yashna Yogi", email: "yashna@college.edu", avatarUrl: "",
    githubUsername: "yogiyashna31-source", leetcodeUsername: "yashnayogi", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 32,
    leetcode: { totalSolved: 113, easy: 26, medium: 30, hard: 0, streak: 3, ranking: 240659, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 61, totalRepos: 5, totalPRs: 5, totalStars: 5, languages: [{ name: "JavaScript", percentage: 50 }, { name: "SQL", percentage: 20 }, { name: "Java", percentage: 30 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "67", name: "Ichcha Mehrishi", email: "ichcha@college.edu", avatarUrl: "",
    githubUsername: "ichcha03", leetcodeUsername: "Ichcha31", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 37,
    leetcode: { totalSolved: 103, easy: 43, medium: 46, hard: 1, streak: 6, ranking: 221704, recentSubmissions: generateSubmissions(0) },
    github: { totalCommits: 107, totalRepos: 7, totalPRs: 6, totalStars: 0, languages: [{ name: "C++", percentage: 43 }, { name: "Rust", percentage: 57 }], commitHistory: generateCommitHistory(0) },
  },
  {
    id: "68", name: "Balkrishna Goswami", email: "balkrishna@college.edu", avatarUrl: "",
    githubUsername: "THEBKGOSWAMI08", leetcodeUsername: "thebkgoswami", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 92,
    leetcode: { totalSolved: 334, easy: 124, medium: 198, hard: 63, streak: 41, ranking: 27701, recentSubmissions: generateSubmissions(3) },
    github: { totalCommits: 1129, totalRepos: 19, totalPRs: 56, totalStars: 123, languages: [{ name: "C++", percentage: 41 }, { name: "Python", percentage: 34 }, { name: "C", percentage: 25 }], commitHistory: generateCommitHistory(5) },
  },
  {
    id: "69", name: "Saumya Upadhyay", email: "saumya@college.edu", avatarUrl: "",
    githubUsername: "saumya-200", leetcodeUsername: "saumya", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 57,
    leetcode: { totalSolved: 242, easy: 76, medium: 107, hard: 27, streak: 18, ranking: 63506, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 281, totalRepos: 14, totalPRs: 16, totalStars: 11, languages: [{ name: "SQL", percentage: 60 }, { name: "Java", percentage: 40 }], commitHistory: generateCommitHistory(3) },
  },
  {
    id: "70", name: "Sri Amarnadh Elisari", email: "sri@college.edu", avatarUrl: "",
    githubUsername: "Sriamarnadh-Tech", leetcodeUsername: "sriamarnadh90307", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 20,
    leetcode: { totalSolved: 32, easy: 57, medium: 20, hard: 2, streak: 7, ranking: 248000, recentSubmissions: generateSubmissions(0) },
    github: { totalCommits: 82, totalRepos: 2, totalPRs: 8, totalStars: 1, languages: [{ name: "TypeScript", percentage: 43 }, { name: "CSS", percentage: 47 }, { name: "Python", percentage: 10 }], commitHistory: generateCommitHistory(0) },
  },
  {
    id: "71", name: "Tanishka Jadaun", email: "tanishka@college.edu", avatarUrl: "",
    githubUsername: "TanishkaJadaun", leetcodeUsername: "Tanishka_Jadaun", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 24,
    leetcode: { totalSolved: 84, easy: 37, medium: 12, hard: 10, streak: 7, ranking: 106758, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 63, totalRepos: 2, totalPRs: 5, totalStars: 1, languages: [{ name: "C++", percentage: 44 }, { name: "Python", percentage: 56 }], commitHistory: generateCommitHistory(0) },
  },
  {
    id: "72", name: "Dhruv Tiwari", email: "dhruv@college.edu", avatarUrl: "",
    githubUsername: "dhruv-tiwari12", leetcodeUsername: "Dhruv_tiwari01", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 36,
    leetcode: { totalSolved: 49, easy: 23, medium: 35, hard: 7, streak: 7, ranking: 194906, recentSubmissions: generateSubmissions(0) },
    github: { totalCommits: 161, totalRepos: 6, totalPRs: 1, totalStars: 3, languages: [{ name: "Rust", percentage: 36 }, { name: "SQL", percentage: 50 }, { name: "Python", percentage: 14 }], commitHistory: generateCommitHistory(0) },
  },
  {
    id: "73", name: "Devansh Sharma", email: "devansh@college.edu", avatarUrl: "",
    githubUsername: "devanshx72", leetcodeUsername: "devanshx72", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 33,
    leetcode: { totalSolved: 47, easy: 77, medium: 50, hard: 7, streak: 1, ranking: 121178, recentSubmissions: generateSubmissions(0) },
    github: { totalCommits: 112, totalRepos: 6, totalPRs: 2, totalStars: 0, languages: [{ name: "Go", percentage: 44 }, { name: "CSS", percentage: 34 }, { name: "HTML", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "74", name: "Varun Kumar Srivastava", email: "varun@college.edu", avatarUrl: "",
    githubUsername: "Varun1207-code", leetcodeUsername: "vs20021207", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 63,
    leetcode: { totalSolved: 175, easy: 120, medium: 74, hard: 37, streak: 18, ranking: 76132, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 360, totalRepos: 14, totalPRs: 22, totalStars: 33, languages: [{ name: "Rust", percentage: 38 }, { name: "Go", percentage: 40 }, { name: "SQL", percentage: 22 }], commitHistory: generateCommitHistory(3) },
  },
  {
    id: "75", name: "Ishant Singh", email: "ishant@college.edu", avatarUrl: "",
    githubUsername: "ishant2023", leetcodeUsername: "ishant__cs23", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 71,
    leetcode: { totalSolved: 215, easy: 93, medium: 79, hard: 31, streak: 15, ranking: 44399, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 296, totalRepos: 9, totalPRs: 10, totalStars: 18, languages: [{ name: "HTML", percentage: 58 }, { name: "Python", percentage: 42 }], commitHistory: generateCommitHistory(3) },
  },
  {
    id: "76", name: "Tarun Goyal", email: "tarun@college.edu", avatarUrl: "",
    githubUsername: "tarungoyalxiia1416-droid", leetcodeUsername: "vQ1OLs0Ipl", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 37,
    leetcode: { totalSolved: 104, easy: 30, medium: 31, hard: 5, streak: 7, ranking: 210870, recentSubmissions: generateSubmissions(0) },
    github: { totalCommits: 43, totalRepos: 4, totalPRs: 4, totalStars: 2, languages: [{ name: "SQL", percentage: 47 }, { name: "Rust", percentage: 53 }], commitHistory: generateCommitHistory(0) },
  },
  {
    id: "77", name: "Pragati Agrawal", email: "pragati@college.edu", avatarUrl: "",
    githubUsername: "prati019", leetcodeUsername: "pr44ti", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 31,
    leetcode: { totalSolved: 114, easy: 29, medium: 22, hard: 9, streak: 2, ranking: 212489, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 173, totalRepos: 8, totalPRs: 8, totalStars: 0, languages: [{ name: "C++", percentage: 69 }, { name: "Kotlin", percentage: 31 }], commitHistory: generateCommitHistory(0) },
  },
  {
    id: "78", name: "Sujal Singh", email: "sujal@college.edu", avatarUrl: "",
    githubUsername: "SujalSingh9252", leetcodeUsername: "sujalsingh_7", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 50,
    leetcode: { totalSolved: 196, easy: 79, medium: 132, hard: 31, streak: 14, ranking: 44560, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 322, totalRepos: 18, totalPRs: 8, totalStars: 7, languages: [{ name: "Rust", percentage: 46 }, { name: "C", percentage: 29 }, { name: "TypeScript", percentage: 25 }], commitHistory: generateCommitHistory(3) },
  },
  {
    id: "79", name: "Parul Singh", email: "parul@college.edu", avatarUrl: "",
    githubUsername: "Parul-singh13", leetcodeUsername: "parulsingh13p", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 44,
    leetcode: { totalSolved: 41, easy: 21, medium: 14, hard: 2, streak: 7, ranking: 113044, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 50, totalRepos: 4, totalPRs: 7, totalStars: 5, languages: [{ name: "Go", percentage: 51 }, { name: "C++", percentage: 23 }, { name: "Java", percentage: 26 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "80", name: "Gouransh Agarwal", email: "gouransh@college.edu", avatarUrl: "",
    githubUsername: "GouranshAgarwal", leetcodeUsername: "m1z7m5J7iT", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 53,
    leetcode: { totalSolved: 222, easy: 113, medium: 135, hard: 25, streak: 16, ranking: 60212, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 273, totalRepos: 11, totalPRs: 20, totalStars: 24, languages: [{ name: "C++", percentage: 64 }, { name: "Java", percentage: 36 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "81", name: "Kunj Bhasin", email: "kunj@college.edu", avatarUrl: "",
    githubUsername: "kunj-16", leetcodeUsername: "kunj_16", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 83,
    leetcode: { totalSolved: 374, easy: 120, medium: 155, hard: 40, streak: 35, ranking: 24111, recentSubmissions: generateSubmissions(5) },
    github: { totalCommits: 879, totalRepos: 19, totalPRs: 54, totalStars: 108, languages: [{ name: "JavaScript", percentage: 48 }, { name: "Go", percentage: 20 }, { name: "Python", percentage: 32 }], commitHistory: generateCommitHistory(4) },
  },
  {
    id: "82", name: "Disha Gupta", email: "disha@college.edu", avatarUrl: "",
    githubUsername: "Disha4346", leetcodeUsername: "Disha_Gupta", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 52,
    leetcode: { totalSolved: 230, easy: 106, medium: 114, hard: 28, streak: 14, ranking: 67373, recentSubmissions: generateSubmissions(3) },
    github: { totalCommits: 398, totalRepos: 9, totalPRs: 20, totalStars: 5, languages: [{ name: "Kotlin", percentage: 48 }, { name: "C", percentage: 23 }, { name: "JavaScript", percentage: 29 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "83", name: "Suraj Kumar", email: "suraj@college.edu", avatarUrl: "",
    githubUsername: "SurajKumar2005", leetcodeUsername: "surajkumargupta0901", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 93,
    leetcode: { totalSolved: 402, easy: 133, medium: 150, hard: 65, streak: 47, ranking: 20167, recentSubmissions: generateSubmissions(3) },
    github: { totalCommits: 1047, totalRepos: 22, totalPRs: 51, totalStars: 139, languages: [{ name: "HTML", percentage: 46 }, { name: "Kotlin", percentage: 54 }], commitHistory: generateCommitHistory(4) },
  },
  {
    id: "84", name: "Stuti Agrawal", email: "stuti@college.edu", avatarUrl: "",
    githubUsername: "stuti0426", leetcodeUsername: "Stuti04_", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 31,
    leetcode: { totalSolved: 109, easy: 33, medium: 20, hard: 1, streak: 2, ranking: 167100, recentSubmissions: generateSubmissions(0) },
    github: { totalCommits: 80, totalRepos: 3, totalPRs: 2, totalStars: 5, languages: [{ name: "Rust", percentage: 49 }, { name: "CSS", percentage: 41 }, { name: "SQL", percentage: 10 }], commitHistory: generateCommitHistory(0) },
  }
];

export const clusterSummaries: ClusterSummary[] = [
  { name: "Advanced", count: students.filter(s => s.cluster === "Advanced").length, avgCpi: Math.round(students.filter(s => s.cluster === "Advanced").reduce((a, s) => a + s.cpi, 0) / students.filter(s => s.cluster === "Advanced").length), color: "hsl(152, 60%, 50%)" },
  { name: "Intermediate", count: students.filter(s => s.cluster === "Intermediate").length, avgCpi: Math.round(students.filter(s => s.cluster === "Intermediate").reduce((a, s) => a + s.cpi, 0) / students.filter(s => s.cluster === "Intermediate").length), color: "hsl(210, 80%, 55%)" },
  { name: "Beginner", count: students.filter(s => s.cluster === "Beginner").length, avgCpi: Math.round(students.filter(s => s.cluster === "Beginner").reduce((a, s) => a + s.cpi, 0) / students.filter(s => s.cluster === "Beginner").length), color: "hsl(38, 92%, 50%)" },
];
