import { Student, ClusterSummary } from "./types";


const generateCommitHistory = (base: number) => {
  const data = [];
  for (let i = 29; i >= 0; i--) {
    const d = new Date();
    d.setDate(d.getDate() - i);
    data.push({
      date: d.toISOString().split("T")[0],
      count: Math.max(0, Math.floor(base + Math.random() * 6 - 2)),
    });
  }
  return data;
};

const generateSubmissions = (base: number) => {
  const data = [];
  for (let i = 29; i >= 0; i--) {
    const d = new Date();
    d.setDate(d.getDate() - i);
    data.push({
      date: d.toISOString().split("T")[0],
      count: Math.max(0, Math.floor(base + Math.random() * 4 - 1)),
    });
  }
  return data;
};

export const students: Student[] = [
  {
    id: "1", name: "Mayank Sharma", email: "mayank@college.edu", avatarUrl: "",
    githubUsername: "mayank12sharma", leetcodeUsername: "mayank-05-old", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 78,
    leetcode: { totalSolved: 446, easy: 161, medium: 236, hard: 49, streak: 25, ranking: 233393, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 1692, totalRepos: 94, totalPRs: 29, totalStars: 1, languages: [{ name: "Python", percentage: 21 }, { name: "SCSS", percentage: 21 }, { name: "HTML", percentage: 21 }], commitHistory: generateCommitHistory(9) },
  },
  {
    id: "2", name: "Anuj Kumar", email: "anuj@college.edu", avatarUrl: "",
    githubUsername: "AnujKumar1204", leetcodeUsername: "anuj1210", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 22,
    leetcode: { totalSolved: 193, easy: 104, medium: 89, hard: 0, streak: 28, ranking: 787722, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 184, totalRepos: 8, totalPRs: 3, totalStars: 0, languages: [{ name: "Python", percentage: 60 }, { name: "JavaScript", percentage: 20 }, { name: "Jupyter Notebook", percentage: 20 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "3", name: "Prerita Saini", email: "prerita@college.edu", avatarUrl: "",
    githubUsername: "preritasaini1", leetcodeUsername: "Prerita_1", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 71,
    leetcode: { totalSolved: 587, easy: 281, medium: 266, hard: 40, streak: 12, ranking: 131598, recentSubmissions: generateSubmissions(3) },
    github: { totalCommits: 589, totalRepos: 31, totalPRs: 9, totalStars: 1, languages: [{ name: "Python", percentage: 38 }, { name: "Jupyter Notebook", percentage: 38 }, { name: "JavaScript", percentage: 12 }], commitHistory: generateCommitHistory(3) },
  },
  {
    id: "4", name: "Parth Garg", email: "parth@college.edu", avatarUrl: "",
    githubUsername: "Parthgarg27", leetcodeUsername: "parth_garg77", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 33,
    leetcode: { totalSolved: 192, easy: 88, medium: 84, hard: 20, streak: 26, ranking: 797350, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 950, totalRepos: 25, totalPRs: 7, totalStars: 0, languages: [{ name: "Python", percentage: 53 }, { name: "JavaScript", percentage: 26 }, { name: "Java", percentage: 11 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "5", name: "Sarvagya Saxena", email: "sarvagya@college.edu", avatarUrl: "",
    githubUsername: "SarvagyaSaxena101", leetcodeUsername: "sarvagyasaxena2006", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 58,
    leetcode: { totalSolved: 389, easy: 205, medium: 172, hard: 12, streak: 23, ranking: 296102, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 1008, totalRepos: 36, totalPRs: 10, totalStars: 1, languages: [{ name: "Python", percentage: 60 }, { name: "Jupyter Notebook", percentage: 28 }, { name: "Kotlin", percentage: 8 }], commitHistory: generateCommitHistory(3) },
  },
  {
    id: "6", name: "Rudraksh Mahajan", email: "rudraksh@college.edu", avatarUrl: "",
    githubUsername: "raiden9420", leetcodeUsername: "Rudrax9420", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 43,
    leetcode: { totalSolved: 269, easy: 194, medium: 74, hard: 1, streak: 5, ranking: 519575, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 306, totalRepos: 18, totalPRs: 7, totalStars: 15, languages: [{ name: "Python", percentage: 33 }, { name: "TypeScript", percentage: 27 }, { name: "Java", percentage: 13 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "7", name: "Uday Chauhan", email: "uday@college.edu", avatarUrl: "",
    githubUsername: "Udaychauhan1724", leetcodeUsername: "Uday_Chauhan04", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 38,
    leetcode: { totalSolved: 332, easy: 165, medium: 149, hard: 18, streak: 12, ranking: 382803, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 434, totalRepos: 14, totalPRs: 2, totalStars: 0, languages: [{ name: "Python", percentage: 62 }, { name: "Jupyter Notebook", percentage: 12 }, { name: "JavaScript", percentage: 12 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "8", name: "Ansham Maurya", email: "ansham@college.edu", avatarUrl: "",
    githubUsername: "ANSHAM1", leetcodeUsername: "Ansham_Maurya", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 35,
    leetcode: { totalSolved: 261, easy: 112, medium: 130, hard: 19, streak: 22, ranking: 541135, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 189, totalRepos: 9, totalPRs: 7, totalStars: 13, languages: [{ name: "C++", percentage: 62 }, { name: "Python", percentage: 12 }, { name: "Rust", percentage: 12 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "9", name: "Aavya", email: "aavya@college.edu", avatarUrl: "",
    githubUsername: "aavya1234", leetcodeUsername: "Aavya1234", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 31,
    leetcode: { totalSolved: 169, easy: 85, medium: 73, hard: 11, streak: 12, ranking: 908756, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 696, totalRepos: 24, totalPRs: 10, totalStars: 1, languages: [{ name: "Python", percentage: 53 }, { name: "JavaScript", percentage: 29 }, { name: "TypeScript", percentage: 6 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "10", name: "Ashish Kumar", email: "ashish@college.edu", avatarUrl: "",
    githubUsername: "ashishkumar03440", leetcodeUsername: "ashsih03440", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 23,
    leetcode: { totalSolved: 20, easy: 20, medium: 32, hard: 5, streak: 3, ranking: 172842, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 651, totalRepos: 31, totalPRs: 13, totalStars: 1, languages: [{ name: "Python", percentage: 36 }, { name: "JavaScript", percentage: 14 }, { name: "Jupyter Notebook", percentage: 14 }], commitHistory: generateCommitHistory(3) },
  },
  {
    id: "11", name: "Shiv Kumar", email: "shiv@college.edu", avatarUrl: "",
    githubUsername: "optimus-shiv", leetcodeUsername: "Shivkumar117", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 5,
    leetcode: { totalSolved: 33, easy: 15, medium: 29, hard: 1, streak: 6, ranking: 194104, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 102, totalRepos: 3, totalPRs: 3, totalStars: 0, languages: [{ name: "Python", percentage: 100 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "12", name: "Yashraj Mishra", email: "yashraj@college.edu", avatarUrl: "",
    githubUsername: "yashrajmishra40", leetcodeUsername: "yashraj_2315800095", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 9,
    leetcode: { totalSolved: 25, easy: 39, medium: 39, hard: 1, streak: 2, ranking: 199230, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 352, totalRepos: 11, totalPRs: 5, totalStars: 0, languages: [{ name: "Python", percentage: 44 }, { name: "JavaScript", percentage: 22 }, { name: "Java", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "13", name: "Pankhuri Agrawal", email: "pankhuri@college.edu", avatarUrl: "",
    githubUsername: "PankhuriAgrawal607", leetcodeUsername: "pankhuriagrawal_607", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 46,
    leetcode: { totalSolved: 380, easy: 213, medium: 154, hard: 13, streak: 25, ranking: 314829, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 612, totalRepos: 18, totalPRs: 9, totalStars: 2, languages: [{ name: "Python", percentage: 30 }, { name: "TypeScript", percentage: 20 }, { name: "HTML", percentage: 20 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "14", name: "Harshit Chaudhary", email: "harshit@college.edu", avatarUrl: "",
    githubUsername: "harshitchaudha", leetcodeUsername: "harshitchaudhry109", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 32,
    leetcode: { totalSolved: 262, easy: 101, medium: 133, hard: 28, streak: 23, ranking: 538434, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 294, totalRepos: 14, totalPRs: 3, totalStars: 0, languages: [{ name: "Python", percentage: 67 }, { name: "JavaScript", percentage: 22 }, { name: "HTML", percentage: 11 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "15", name: "Somesh Rajput", email: "somesh@college.edu", avatarUrl: "",
    githubUsername: "somesh78", leetcodeUsername: "rajputsomesh78", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 19,
    leetcode: { totalSolved: 70, easy: 47, medium: 23, hard: 0, streak: 6, ranking: 1937272, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 720, totalRepos: 20, totalPRs: 7, totalStars: 0, languages: [{ name: "Python", percentage: 46 }, { name: "Jupyter Notebook", percentage: 23 }, { name: "JavaScript", percentage: 15 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "16", name: "Sneha Chaudhary", email: "sneha@college.edu", avatarUrl: "",
    githubUsername: "SNEHA-CHAUDHARY03", leetcodeUsername: "sneha_chaudhary", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 29,
    leetcode: { totalSolved: 272, easy: 131, medium: 122, hard: 19, streak: 29, ranking: 511746, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 216, totalRepos: 9, totalPRs: 2, totalStars: 0, languages: [{ name: "Python", percentage: 57 }, { name: "Jupyter Notebook", percentage: 43 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "17", name: "Vaishvik Sharma", email: "vaishvik@college.edu", avatarUrl: "",
    githubUsername: "vaishviksharma", leetcodeUsername: "vaishviksharma7860", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 13,
    leetcode: { totalSolved: 22, easy: 6, medium: 16, hard: 0, streak: 12, ranking: 3828603, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 288, totalRepos: 16, totalPRs: 9, totalStars: 0, languages: [{ name: "JavaScript", percentage: 43 }, { name: "Python", percentage: 21 }, { name: "HTML", percentage: 21 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "18", name: "Siddhartha Khandelwal", email: "siddhartha@college.edu", avatarUrl: "",
    githubUsername: "Siddharthakhandelwal", leetcodeUsername: "siddharthakhandelwal9", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 32,
    leetcode: { totalSolved: 126, easy: 67, medium: 55, hard: 4, streak: 13, ranking: 1213935, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 667, totalRepos: 23, totalPRs: 10, totalStars: 11, languages: [{ name: "Python", percentage: 50 }, { name: "TypeScript", percentage: 22 }, { name: "Jupyter Notebook", percentage: 17 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "19", name: "Isha Vashishtha", email: "isha@college.edu", avatarUrl: "",
    githubUsername: "Isha-Vashishtha", leetcodeUsername: "Isha_vashishtha", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 68,
    leetcode: { totalSolved: 548, easy: 217, medium: 276, hard: 55, streak: 10, ranking: 153452, recentSubmissions: generateSubmissions(3) },
    github: { totalCommits: 806, totalRepos: 31, totalPRs: 13, totalStars: 1, languages: [{ name: "Python", percentage: 33 }, { name: "JavaScript", percentage: 24 }, { name: "Jupyter Notebook", percentage: 19 }], commitHistory: generateCommitHistory(3) },
  },
  {
    id: "20", name: "Akshat Somani", email: "akshat@college.edu", avatarUrl: "",
    githubUsername: "AkshatGLA", leetcodeUsername: "akshatsachinsomani", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 49,
    leetcode: { totalSolved: 335, easy: 188, medium: 134, hard: 13, streak: 11, ranking: 377433, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 1080, totalRepos: 30, totalPRs: 12, totalStars: 0, languages: [{ name: "JavaScript", percentage: 35 }, { name: "Python", percentage: 22 }, { name: "HTML", percentage: 17 }], commitHistory: generateCommitHistory(3) },
  },
  {
    id: "21", name: "Aaditya Ranjan Moitra", email: "aaditya@college.edu", avatarUrl: "",
    githubUsername: "AadityaSukhoi", leetcodeUsername: "CodingAvgeek", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 22,
    leetcode: { totalSolved: 23, easy: 9, medium: 14, hard: 0, streak: 27, ranking: 3768200, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 1008, totalRepos: 28, totalPRs: 8, totalStars: 2, languages: [{ name: "Jupyter Notebook", percentage: 40 }, { name: "Python", percentage: 35 }, { name: "Java", percentage: 10 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "22", name: "Prashant", email: "prashant@college.edu", avatarUrl: "",
    githubUsername: "prashantsorout001", leetcodeUsername: "Prashant_sorout01", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 14,
    leetcode: { totalSolved: 82, easy: 56, medium: 22, hard: 4, streak: 24, ranking: 1727779, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 385, totalRepos: 11, totalPRs: 3, totalStars: 0, languages: [{ name: "HTML", percentage: 62 }, { name: "Python", percentage: 25 }, { name: "Jupyter Notebook", percentage: 12 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "23", name: "Ishita Agarwal", email: "ishita@college.edu", avatarUrl: "",
    githubUsername: "ishitagarwal10", leetcodeUsername: "Ishita_Agarwal10", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 17,
    leetcode: { totalSolved: 150, easy: 80, medium: 59, hard: 11, streak: 22, ranking: 1029798, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 190, totalRepos: 5, totalPRs: 2, totalStars: 1, languages: [{ name: "Java", percentage: 33 }, { name: "Python", percentage: 33 }, { name: "HTML", percentage: 33 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "24", name: "Aeshna Varshney", email: "aeshna@college.edu", avatarUrl: "",
    githubUsername: "aeshnavarshney25", leetcodeUsername: "aeshnavarshney", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 47,
    leetcode: { totalSolved: 405, easy: 216, medium: 172, hard: 17, streak: 10, ranking: 277540, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 493, totalRepos: 17, totalPRs: 9, totalStars: 1, languages: [{ name: "Python", percentage: 45 }, { name: "JavaScript", percentage: 27 }, { name: "TypeScript", percentage: 9 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "25", name: "Lav Saraswat", email: "lav@college.edu", avatarUrl: "",
    githubUsername: "LavSaraswat", leetcodeUsername: "Lav_Saraswat", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 10,
    leetcode: { totalSolved: 39, easy: 26, medium: 12, hard: 1, streak: 13, ranking: 2832102, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 350, totalRepos: 10, totalPRs: 4, totalStars: 0, languages: [{ name: "Python", percentage: 50 }, { name: "Java", percentage: 17 }, { name: "JavaScript", percentage: 17 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "26", name: "Rahul Gupta", email: "rahul@college.edu", avatarUrl: "",
    githubUsername: "Rahul20004", leetcodeUsername: "rg8490832", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 66,
    leetcode: { totalSolved: 319, easy: 119, medium: 171, hard: 29, streak: 26, ranking: 406899, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 1425, totalRepos: 57, totalPRs: 17, totalStars: 1, languages: [{ name: "JavaScript", percentage: 80 }, { name: "HTML", percentage: 20 }], commitHistory: generateCommitHistory(5) },
  },
  {
    id: "27", name: "Pawan Agrawal", email: "pawan@college.edu", avatarUrl: "",
    githubUsername: "Pawan-Agrawall", leetcodeUsername: "Pavan1456", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 39,
    leetcode: { totalSolved: 299, easy: 124, medium: 164, hard: 11, streak: 12, ranking: 448905, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 320, totalRepos: 20, totalPRs: 9, totalStars: 1, languages: [{ name: "Python", percentage: 62 }, { name: "JavaScript", percentage: 12 }, { name: "Java", percentage: 12 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "28", name: "Jayendra Singh", email: "jayendra@college.edu", avatarUrl: "",
    githubUsername: "jayendrasingh22", leetcodeUsername: "JayendraSingh122", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 11,
    leetcode: { totalSolved: 40, easy: 21, medium: 17, hard: 2, streak: 17, ranking: 2785809, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 276, totalRepos: 12, totalPRs: 3, totalStars: 0, languages: [{ name: "Python", percentage: 50 }, { name: "JavaScript", percentage: 25 }, { name: "Java", percentage: 25 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "29", name: "Shivam Rajput", email: "shivam@college.edu", avatarUrl: "",
    githubUsername: "sh1vamRajput", leetcodeUsername: "shivamrajput0537", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 29,
    leetcode: { totalSolved: 193, easy: 81, medium: 95, hard: 17, streak: 11, ranking: 787725, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 594, totalRepos: 18, totalPRs: 9, totalStars: 1, languages: [{ name: "Python", percentage: 50 }, { name: "JavaScript", percentage: 20 }, { name: "Java", percentage: 20 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "30", name: "Archi Agrawal", email: "archi@college.edu", avatarUrl: "",
    githubUsername: "04archi", leetcodeUsername: "04archi", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 33,
    leetcode: { totalSolved: 248, easy: 116, medium: 115, hard: 17, streak: 11, ranking: 579921, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 595, totalRepos: 17, totalPRs: 10, totalStars: 1, languages: [{ name: "JavaScript", percentage: 50 }, { name: "Python", percentage: 20 }, { name: "HTML", percentage: 20 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "31", name: "Nishi Srivastava", email: "nishi@college.edu", avatarUrl: "",
    githubUsername: "NISHISRIVASTAVA123", leetcodeUsername: "NISHI_20", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 27,
    leetcode: { totalSolved: 108, easy: 54, medium: 51, hard: 3, streak: 17, ranking: 1390032, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 575, totalRepos: 25, totalPRs: 8, totalStars: 3, languages: [{ name: "Java", percentage: 44 }, { name: "Python", percentage: 33 }, { name: "C++", percentage: 22 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "32", name: "Raj Shwet Gautam", email: "raj@college.edu", avatarUrl: "",
    githubUsername: "raj11gautam", leetcodeUsername: "Raj112128", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 38,
    leetcode: { totalSolved: 254, easy: 134, medium: 110, hard: 10, streak: 12, ranking: 561466, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 836, totalRepos: 22, totalPRs: 11, totalStars: 4, languages: [{ name: "Python", percentage: 75 }, { name: "C", percentage: 25 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "33", name: "Bhavya Tandon", email: "bhavya@college.edu", avatarUrl: "",
    githubUsername: "bhavyatan", leetcodeUsername: "bhavya__133", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 23,
    leetcode: { totalSolved: 127, easy: 68, medium: 56, hard: 3, streak: 23, ranking: 1205442, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 323, totalRepos: 17, totalPRs: 10, totalStars: 2, languages: [{ name: "Java", percentage: 44 }, { name: "Python", percentage: 33 }, { name: "C++", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "34", name: "Nimit Goyal", email: "nimit@college.edu", avatarUrl: "",
    githubUsername: "nimix26", leetcodeUsername: "_Nimit26", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 15,
    leetcode: { totalSolved: 134, easy: 85, medium: 49, hard: 0, streak: 7, ranking: 1146778, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 210, totalRepos: 6, totalPRs: 2, totalStars: 0, languages: [{ name: "Java", percentage: 44 }, { name: "Python", percentage: 33 }, { name: "C++", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "35", name: "Abhijith Jicks", email: "abhijith@college.edu", avatarUrl: "",
    githubUsername: "abhijithjicks", leetcodeUsername: "abhijithjicks", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 29,
    leetcode: { totalSolved: 172, easy: 69, medium: 88, hard: 15, streak: 30, ranking: 891682, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 486, totalRepos: 18, totalPRs: 10, totalStars: 4, languages: [{ name: "Python", percentage: 50 }, { name: "JavaScript", percentage: 30 }, { name: "HTML", percentage: 20 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "36", name: "Nitin Kumar", email: "nitin@college.edu", avatarUrl: "",
    githubUsername: "Nitin99sogarwal", leetcodeUsername: "nitin514", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 41,
    leetcode: { totalSolved: 312, easy: 193, medium: 113, hard: 6, streak: 24, ranking: 420853, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 608, totalRepos: 19, totalPRs: 4, totalStars: 4, languages: [{ name: "Python", percentage: 75 }, { name: "C", percentage: 25 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "37", name: "Jyotsana Bhardwaj", email: "jyotsana@college.edu", avatarUrl: "",
    githubUsername: "jyotsana15", leetcodeUsername: "Jyotsana_Bhardwaj", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 25,
    leetcode: { totalSolved: 196, easy: 85, medium: 101, hard: 10, streak: 26, ranking: 774441, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 312, totalRepos: 8, totalPRs: 5, totalStars: 5, languages: [{ name: "Python", percentage: 75 }, { name: "C", percentage: 25 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "38", name: "Aryan Tiwari", email: "aryan@college.edu", avatarUrl: "",
    githubUsername: "Aryantiwarib", leetcodeUsername: "Aryan_cs23", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 45,
    leetcode: { totalSolved: 403, easy: 201, medium: 166, hard: 36, streak: 8, ranking: 279976, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 406, totalRepos: 14, totalPRs: 2, totalStars: 3, languages: [{ name: "Java", percentage: 44 }, { name: "Python", percentage: 33 }, { name: "C++", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "39", name: "Parth Sharma", email: "parth@college.edu", avatarUrl: "",
    githubUsername: "parthsharma-7", leetcodeUsername: "parthsharma7", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 15,
    leetcode: { totalSolved: 53, easy: 31, medium: 21, hard: 1, streak: 28, ranking: 2334251, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 403, totalRepos: 13, totalPRs: 3, totalStars: 4, languages: [{ name: "Java", percentage: 44 }, { name: "Python", percentage: 33 }, { name: "C++", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "40", name: "Mukti Mishra", email: "mukti@college.edu", avatarUrl: "",
    githubUsername: "MuktiMishra", leetcodeUsername: "MuktiMishra", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 67,
    leetcode: { totalSolved: 646, easy: 281, medium: 309, hard: 56, streak: 25, ranking: 106147, recentSubmissions: generateSubmissions(4) },
    github: { totalCommits: 266, totalRepos: 14, totalPRs: 7, totalStars: 5, languages: [{ name: "Java", percentage: 44 }, { name: "Python", percentage: 33 }, { name: "C++", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "41", name: "Ayush Mittal", email: "ayush@college.edu", avatarUrl: "",
    githubUsername: "Ayush-AI-ux", leetcodeUsername: "Ayush_Mittal_637", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 43,
    leetcode: { totalSolved: 402, easy: 174, medium: 201, hard: 27, streak: 29, ranking: 280034, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 340, totalRepos: 10, totalPRs: 6, totalStars: 4, languages: [{ name: "Python", percentage: 50 }, { name: "JavaScript", percentage: 30 }, { name: "HTML", percentage: 20 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "42", name: "Arjun Singh Rajput", email: "arjun@college.edu", avatarUrl: "",
    githubUsername: "ArjunRajputGLA", leetcodeUsername: "CodeXI", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 12,
    leetcode: { totalSolved: 82, easy: 11, medium: 12, hard: 5, streak: 4, ranking: 180612, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 102, totalRepos: 6, totalPRs: 7, totalStars: 1, languages: [{ name: "Python", percentage: 50 }, { name: "JavaScript", percentage: 30 }, { name: "HTML", percentage: 20 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "43", name: "Garvit Kedia", email: "garvit@college.edu", avatarUrl: "",
    githubUsername: "Garvit-kedia", leetcodeUsername: "garvitkedia2", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 48,
    leetcode: { totalSolved: 379, easy: 123, medium: 219, hard: 37, streak: 7, ranking: 309177, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 792, totalRepos: 22, totalPRs: 12, totalStars: 1, languages: [{ name: "Java", percentage: 44 }, { name: "Python", percentage: 33 }, { name: "C++", percentage: 22 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "44", name: "Akshansh Maurya", email: "akshansh@college.edu", avatarUrl: "",
    githubUsername: "akshanshmaurya", leetcodeUsername: "Akshansh_maurya", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 60,
    leetcode: { totalSolved: 608, easy: 240, medium: 302, hard: 66, streak: 22, ranking: 120783, recentSubmissions: generateSubmissions(4) },
    github: { totalCommits: 210, totalRepos: 10, totalPRs: 4, totalStars: 2, languages: [{ name: "JavaScript", percentage: 44 }, { name: "TypeScript", percentage: 33 }, { name: "Python", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "45", name: "Harshit Rathi", email: "harshit@college.edu", avatarUrl: "",
    githubUsername: "Rathi2005", leetcodeUsername: "Harshit_Rathi", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 33,
    leetcode: { totalSolved: 264, easy: 125, medium: 128, hard: 11, streak: 27, ranking: 532936, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 406, totalRepos: 14, totalPRs: 9, totalStars: 3, languages: [{ name: "Python", percentage: 75 }, { name: "C", percentage: 25 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "46", name: "Harsh Gupta", email: "harsh@college.edu", avatarUrl: "",
    githubUsername: "HarshGupta-283104", leetcodeUsername: "PH76O5nMoT", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 11,
    leetcode: { totalSolved: 25, easy: 15, medium: 8, hard: 2, streak: 8, ranking: 3602472, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 300, totalRepos: 12, totalPRs: 2, totalStars: 1, languages: [{ name: "Python", percentage: 50 }, { name: "JavaScript", percentage: 30 }, { name: "HTML", percentage: 20 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "47", name: "Parmeet Singh", email: "parmeet@college.edu", avatarUrl: "",
    githubUsername: "parmeetsingh1313n", leetcodeUsername: "parmeetsingh1313n", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 72,
    leetcode: { totalSolved: 668, easy: 303, medium: 307, hard: 58, streak: 23, ranking: 95266, recentSubmissions: generateSubmissions(4) },
    github: { totalCommits: 330, totalRepos: 22, totalPRs: 6, totalStars: 1, languages: [{ name: "Java", percentage: 44 }, { name: "Python", percentage: 33 }, { name: "C++", percentage: 22 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "48", name: "Gaurav Chaudhary", email: "gaurav@college.edu", avatarUrl: "",
    githubUsername: "Gaurav-Chaudhary04", leetcodeUsername: "chaudharygaurav147", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 24,
    leetcode: { totalSolved: 81, easy: 61, medium: 19, hard: 1, streak: 27, ranking: 1743299, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 425, totalRepos: 25, totalPRs: 6, totalStars: 0, languages: [{ name: "Java", percentage: 44 }, { name: "Python", percentage: 33 }, { name: "C++", percentage: 22 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "49", name: "Tejas Mishra", email: "tejas@college.edu", avatarUrl: "",
    githubUsername: "tejas-stack", leetcodeUsername: "tejasmishra04", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 10,
    leetcode: { totalSolved: 39, easy: 31, medium: 8, hard: 0, streak: 15, ranking: 2827116, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 161, totalRepos: 7, totalPRs: 7, totalStars: 4, languages: [{ name: "Java", percentage: 44 }, { name: "Python", percentage: 33 }, { name: "C++", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "50", name: "Madhav Sharma", email: "madhav@college.edu", avatarUrl: "",
    githubUsername: "Madhav7851", leetcodeUsername: "6LjGnB0t8X", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 20,
    leetcode: { totalSolved: 53, easy: 34, medium: 18, hard: 1, streak: 11, ranking: 2340391, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 484, totalRepos: 22, totalPRs: 12, totalStars: 1, languages: [{ name: "JavaScript", percentage: 44 }, { name: "TypeScript", percentage: 33 }, { name: "Python", percentage: 22 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "51", name: "Keshav Agrawal", email: "keshav@college.edu", avatarUrl: "",
    githubUsername: "keshav-agrawal595", leetcodeUsername: "keshav-agrawal1", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 47,
    leetcode: { totalSolved: 400, easy: 173, medium: 201, hard: 26, streak: 30, ranking: 282760, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 324, totalRepos: 18, totalPRs: 10, totalStars: 1, languages: [{ name: "Python", percentage: 50 }, { name: "JavaScript", percentage: 30 }, { name: "HTML", percentage: 20 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "52", name: "Rishabh Jain", email: "rishabh@college.edu", avatarUrl: "",
    githubUsername: "rishabh-jain26", leetcodeUsername: "rishabh_jain_26", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 35,
    leetcode: { totalSolved: 253, easy: 130, medium: 110, hard: 13, streak: 16, ranking: 564178, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 684, totalRepos: 18, totalPRs: 4, totalStars: 3, languages: [{ name: "JavaScript", percentage: 44 }, { name: "TypeScript", percentage: 33 }, { name: "Python", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "53", name: "Sneha Agrawal", email: "sneha@college.edu", avatarUrl: "",
    githubUsername: "Sneha15sep", leetcodeUsername: "snehaagrawal_cs23", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 28,
    leetcode: { totalSolved: 98, easy: 54, medium: 37, hard: 7, streak: 26, ranking: 1510103, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 400, totalRepos: 25, totalPRs: 12, totalStars: 5, languages: [{ name: "Python", percentage: 50 }, { name: "JavaScript", percentage: 30 }, { name: "HTML", percentage: 20 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "54", name: "Om Lakshkar", email: "om@college.edu", avatarUrl: "",
    githubUsername: "Omlakshkar07", leetcodeUsername: "omlakshkar07", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 17,
    leetcode: { totalSolved: 78, easy: 29, medium: 41, hard: 8, streak: 28, ranking: 1791476, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 315, totalRepos: 15, totalPRs: 6, totalStars: 0, languages: [{ name: "Java", percentage: 44 }, { name: "Python", percentage: 33 }, { name: "C++", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "55", name: "Anamika Lodhi", email: "anamika@college.edu", avatarUrl: "",
    githubUsername: "anamikalodhi01", leetcodeUsername: "anamikalodhi01", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 49,
    leetcode: { totalSolved: 422, easy: 211, medium: 184, hard: 27, streak: 22, ranking: 256507, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 380, totalRepos: 19, totalPRs: 8, totalStars: 1, languages: [{ name: "JavaScript", percentage: 44 }, { name: "TypeScript", percentage: 33 }, { name: "Python", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "56", name: "Karunendra Nath Dwivedy", email: "karunendra@college.edu", avatarUrl: "",
    githubUsername: "Karunendra27", leetcodeUsername: "Karunendra_Dwivedy", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 25,
    leetcode: { totalSolved: 204, easy: 86, medium: 106, hard: 12, streak: 19, ranking: 739494, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 480, totalRepos: 12, totalPRs: 3, totalStars: 0, languages: [{ name: "JavaScript", percentage: 44 }, { name: "TypeScript", percentage: 33 }, { name: "Python", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "57", name: "Nikhil Singh", email: "nikhil@college.edu", avatarUrl: "",
    githubUsername: "Fauzdarnikhil", leetcodeUsername: "nikhilsingh1477", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 10,
    leetcode: { totalSolved: 26, easy: 44, medium: 5, hard: 1, streak: 4, ranking: 297542, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 300, totalRepos: 10, totalPRs: 4, totalStars: 3, languages: [{ name: "JavaScript", percentage: 44 }, { name: "TypeScript", percentage: 33 }, { name: "Python", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "58", name: "Ronit Singh", email: "ronit@college.edu", avatarUrl: "",
    githubUsername: "RonitSingh01", leetcodeUsername: "ronitsingh12", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 11,
    leetcode: { totalSolved: 72, easy: 42, medium: 26, hard: 4, streak: 17, ranking: 1898386, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 90, totalRepos: 6, totalPRs: 6, totalStars: 1, languages: [{ name: "JavaScript", percentage: 44 }, { name: "TypeScript", percentage: 33 }, { name: "Python", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "59", name: "Utkarsh Maheshwari", email: "utkarsh@college.edu", avatarUrl: "",
    githubUsername: "utkarsh9916", leetcodeUsername: "utkarsh", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 18,
    leetcode: { totalSolved: 53, easy: 39, medium: 23, hard: 6, streak: 9, ranking: 282607, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 480, totalRepos: 20, totalPRs: 7, totalStars: 1, languages: [{ name: "Java", percentage: 44 }, { name: "Python", percentage: 33 }, { name: "C++", percentage: 22 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "60", name: "Chintakayala Venkata Abhishek", email: "chintakayala@college.edu", avatarUrl: "",
    githubUsername: "VenkataAbhishekTech", leetcodeUsername: "Chintakayala_Venkata_Abhishek", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 29,
    leetcode: { totalSolved: 128, easy: 55, medium: 65, hard: 8, streak: 6, ranking: 1198012, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 874, totalRepos: 23, totalPRs: 10, totalStars: 5, languages: [{ name: "Python", percentage: 50 }, { name: "JavaScript", percentage: 30 }, { name: "HTML", percentage: 20 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "61", name: "Krishna Bansal", email: "krishna@college.edu", avatarUrl: "",
    githubUsername: "KrishnaBansal63", leetcodeUsername: "krishnabansal0592005", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 19,
    leetcode: { totalSolved: 157, easy: 79, medium: 67, hard: 11, streak: 6, ranking: 980639, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 186, totalRepos: 6, totalPRs: 2, totalStars: 4, languages: [{ name: "JavaScript", percentage: 44 }, { name: "TypeScript", percentage: 33 }, { name: "Python", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "62", name: "Aditya Pratap Singh", email: "aditya@college.edu", avatarUrl: "",
    githubUsername: "Adityaa-Pratap-Singh", leetcodeUsername: "its_aditya243", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 27,
    leetcode: { totalSolved: 156, easy: 86, medium: 57, hard: 13, streak: 6, ranking: 987119, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 357, totalRepos: 21, totalPRs: 6, totalStars: 0, languages: [{ name: "Java", percentage: 44 }, { name: "Python", percentage: 33 }, { name: "C++", percentage: 22 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "63", name: "Om Makhija", email: "om@college.edu", avatarUrl: "",
    githubUsername: "OmMakhija", leetcodeUsername: "om_makhija", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 21,
    leetcode: { totalSolved: 135, easy: 87, medium: 45, hard: 3, streak: 26, ranking: 1139298, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 396, totalRepos: 12, totalPRs: 5, totalStars: 3, languages: [{ name: "Python", percentage: 50 }, { name: "JavaScript", percentage: 30 }, { name: "HTML", percentage: 20 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "64", name: "Aditya Pachaury", email: "aditya@college.edu", avatarUrl: "",
    githubUsername: "adityapachaury", leetcodeUsername: "aditya_pachaury", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 27,
    leetcode: { totalSolved: 129, easy: 76, medium: 50, hard: 3, streak: 23, ranking: 1188243, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 672, totalRepos: 24, totalPRs: 11, totalStars: 0, languages: [{ name: "Python", percentage: 50 }, { name: "JavaScript", percentage: 30 }, { name: "HTML", percentage: 20 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "65", name: "Srikant Choubey", email: "srikant@college.edu", avatarUrl: "",
    githubUsername: "Srikant-03", leetcodeUsername: "Srikant_04", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 13,
    leetcode: { totalSolved: 40, easy: 15, medium: 23, hard: 2, streak: 13, ranking: 2790253, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 242, totalRepos: 11, totalPRs: 5, totalStars: 5, languages: [{ name: "Python", percentage: 75 }, { name: "C", percentage: 25 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "66", name: "Yashna Yogi", email: "yashna@college.edu", avatarUrl: "",
    githubUsername: "yogiyashna31-source", leetcodeUsername: "yashnayogi", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 20,
    leetcode: { totalSolved: 137, easy: 62, medium: 62, hard: 13, streak: 17, ranking: 1123071, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 261, totalRepos: 9, totalPRs: 6, totalStars: 5, languages: [{ name: "Python", percentage: 75 }, { name: "C", percentage: 25 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "67", name: "Ichcha Mehrishi", email: "ichcha@college.edu", avatarUrl: "",
    githubUsername: "ichcha03", leetcodeUsername: "Ichcha31", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 16,
    leetcode: { totalSolved: 132, easy: 88, medium: 43, hard: 1, streak: 29, ranking: 1163957, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 238, totalRepos: 7, totalPRs: 1, totalStars: 0, languages: [{ name: "JavaScript", percentage: 44 }, { name: "TypeScript", percentage: 33 }, { name: "Python", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "68", name: "Balkrishna Goswami", email: "balkrishna@college.edu", avatarUrl: "",
    githubUsername: "THEBKGOSWAMI08", leetcodeUsername: "thebkgoswami", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 25,
    leetcode: { totalSolved: 111, easy: 83, medium: 27, hard: 1, streak: 7, ranking: 1358329, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 418, totalRepos: 22, totalPRs: 10, totalStars: 1, languages: [{ name: "Python", percentage: 75 }, { name: "C", percentage: 25 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "69", name: "Saumya Upadhyay", email: "saumya@college.edu", avatarUrl: "",
    githubUsername: "saumya-200", leetcodeUsername: "saumya", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 20,
    leetcode: { totalSolved: 28, easy: 25, medium: 28, hard: 4, streak: 8, ranking: 141352, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 748, totalRepos: 22, totalPRs: 5, totalStars: 5, languages: [{ name: "Python", percentage: 75 }, { name: "C", percentage: 25 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "70", name: "Sri Amarnadh Elisari", email: "sri@college.edu", avatarUrl: "",
    githubUsername: "Sriamarnadh-Tech", leetcodeUsername: "sriamarnadh90307", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 24,
    leetcode: { totalSolved: 97, easy: 41, medium: 46, hard: 10, streak: 26, ranking: 1521933, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 418, totalRepos: 22, totalPRs: 9, totalStars: 2, languages: [{ name: "Python", percentage: 50 }, { name: "JavaScript", percentage: 30 }, { name: "HTML", percentage: 20 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "71", name: "Tanishka Jadaun", email: "tanishka@college.edu", avatarUrl: "",
    githubUsername: "TanishkaJadaun", leetcodeUsername: "Tanishka_Jadaun", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 24,
    leetcode: { totalSolved: 190, easy: 107, medium: 70, hard: 13, streak: 8, ranking: 801909, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 184, totalRepos: 8, totalPRs: 4, totalStars: 5, languages: [{ name: "Java", percentage: 44 }, { name: "Python", percentage: 33 }, { name: "C++", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "72", name: "Dhruv Tiwari", email: "dhruv@college.edu", avatarUrl: "",
    githubUsername: "dhruv-tiwari12", leetcodeUsername: "Dhruv_tiwari01", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 13,
    leetcode: { totalSolved: 33, easy: 16, medium: 13, hard: 4, streak: 24, ranking: 3105495, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 231, totalRepos: 11, totalPRs: 5, totalStars: 5, languages: [{ name: "Python", percentage: 75 }, { name: "C", percentage: 25 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "73", name: "Devansh Sharma", email: "devansh@college.edu", avatarUrl: "",
    githubUsername: "devanshx72", leetcodeUsername: "devanshx72", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 25,
    leetcode: { totalSolved: 126, easy: 64, medium: 56, hard: 6, streak: 21, ranking: 1214027, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 340, totalRepos: 20, totalPRs: 10, totalStars: 2, languages: [{ name: "Python", percentage: 50 }, { name: "JavaScript", percentage: 30 }, { name: "HTML", percentage: 20 }], commitHistory: generateCommitHistory(2) },
  },
  {
    id: "74", name: "Varun Kumar Srivastava", email: "varun@college.edu", avatarUrl: "",
    githubUsername: "Varun1207-code", leetcodeUsername: "vs20021207", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 11,
    leetcode: { totalSolved: 80, easy: 45, medium: 33, hard: 2, streak: 13, ranking: 1759774, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 234, totalRepos: 6, totalPRs: 2, totalStars: 0, languages: [{ name: "Python", percentage: 75 }, { name: "C", percentage: 25 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "75", name: "Ishant Singh", email: "ishant@college.edu", avatarUrl: "",
    githubUsername: "ishant2023", leetcodeUsername: "ishant__cs23", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 10,
    leetcode: { totalSolved: 4, easy: 3, medium: 1, hard: 0, streak: 25, ranking: 5000001, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 416, totalRepos: 13, totalPRs: 8, totalStars: 1, languages: [{ name: "JavaScript", percentage: 44 }, { name: "TypeScript", percentage: 33 }, { name: "Python", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "76", name: "Tarun Goyal", email: "tarun@college.edu", avatarUrl: "",
    githubUsername: "tarungoyalxiia1416-droid", leetcodeUsername: "vQ1OLs0Ipl", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 4,
    leetcode: { totalSolved: 11, easy: 10, medium: 1, hard: 0, streak: 22, ranking: 5000001, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 185, totalRepos: 5, totalPRs: 1, totalStars: 0, languages: [{ name: "Python", percentage: 50 }, { name: "JavaScript", percentage: 30 }, { name: "HTML", percentage: 20 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "77", name: "Pragati Agrawal", email: "pragati@college.edu", avatarUrl: "",
    githubUsername: "prati019", leetcodeUsername: "pr44ti", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 9,
    leetcode: { totalSolved: 45, easy: 27, medium: 15, hard: 3, streak: 22, ranking: 2597972, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 168, totalRepos: 6, totalPRs: 2, totalStars: 2, languages: [{ name: "Java", percentage: 44 }, { name: "Python", percentage: 33 }, { name: "C++", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "78", name: "Sujal Singh", email: "sujal@college.edu", avatarUrl: "",
    githubUsername: "SujalSingh9252", leetcodeUsername: "sujalsingh_7", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 16,
    leetcode: { totalSolved: 65, easy: 36, medium: 24, hard: 5, streak: 6, ranking: 2039124, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 364, totalRepos: 14, totalPRs: 5, totalStars: 2, languages: [{ name: "Python", percentage: 50 }, { name: "JavaScript", percentage: 30 }, { name: "HTML", percentage: 20 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "79", name: "Parul Singh", email: "parul@college.edu", avatarUrl: "",
    githubUsername: "Parul-singh13", leetcodeUsername: "parulsingh13p", department: "CSE", year: 3,
    cluster: "Advanced", cpi: 45,
    leetcode: { totalSolved: 399, easy: 192, medium: 177, hard: 30, streak: 26, ranking: 284965, recentSubmissions: generateSubmissions(2) },
    github: { totalCommits: 312, totalRepos: 12, totalPRs: 8, totalStars: 5, languages: [{ name: "Python", percentage: 50 }, { name: "JavaScript", percentage: 30 }, { name: "HTML", percentage: 20 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "80", name: "Gouransh Agarwal", email: "gouransh@college.edu", avatarUrl: "",
    githubUsername: "GouranshAgarwal", leetcodeUsername: "m1z7m5J7iT", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 19,
    leetcode: { totalSolved: 150, easy: 82, medium: 65, hard: 3, streak: 24, ranking: 1030006, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 360, totalRepos: 9, totalPRs: 3, totalStars: 1, languages: [{ name: "Java", percentage: 44 }, { name: "Python", percentage: 33 }, { name: "C++", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "81", name: "Kunj Bhasin", email: "kunj@college.edu", avatarUrl: "",
    githubUsername: "kunj-16", leetcodeUsername: "kunj_16", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 15,
    leetcode: { totalSolved: 135, easy: 49, medium: 65, hard: 21, streak: 18, ranking: 1139616, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 200, totalRepos: 5, totalPRs: 5, totalStars: 1, languages: [{ name: "Python", percentage: 75 }, { name: "C", percentage: 25 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "82", name: "Disha Gupta", email: "disha@college.edu", avatarUrl: "",
    githubUsername: "Disha4346", leetcodeUsername: "Disha_Gupta", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 10,
    leetcode: { totalSolved: 16, easy: 6, medium: 9, hard: 1, streak: 30, ranking: 4381737, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 480, totalRepos: 12, totalPRs: 3, totalStars: 2, languages: [{ name: "Java", percentage: 44 }, { name: "Python", percentage: 33 }, { name: "C++", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "83", name: "Suraj Kumar", email: "suraj@college.edu", avatarUrl: "",
    githubUsername: "SurajKumar2005", leetcodeUsername: "surajkumargupta0901", department: "CSE", year: 3,
    cluster: "Beginner", cpi: 9,
    leetcode: { totalSolved: 36, easy: 24, medium: 10, hard: 2, streak: 17, ranking: 2958701, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 126, totalRepos: 6, totalPRs: 7, totalStars: 3, languages: [{ name: "Java", percentage: 44 }, { name: "Python", percentage: 33 }, { name: "C++", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  },
  {
    id: "84", name: "Stuti Agrawal", email: "stuti@college.edu", avatarUrl: "",
    githubUsername: "stuti0426", leetcodeUsername: "Stuti04_", department: "CSE", year: 3,
    cluster: "Intermediate", cpi: 32,
    leetcode: { totalSolved: 253, easy: 165, medium: 84, hard: 4, streak: 16, ranking: 564449, recentSubmissions: generateSubmissions(1) },
    github: { totalCommits: 210, totalRepos: 14, totalPRs: 5, totalStars: 1, languages: [{ name: "Java", percentage: 44 }, { name: "Python", percentage: 33 }, { name: "C++", percentage: 22 }], commitHistory: generateCommitHistory(1) },
  }
];

export const clusterSummaries: ClusterSummary[] = [
  { name: "Advanced", count: students.filter(s => s.cluster === "Advanced").length, avgCpi: Math.round(students.filter(s => s.cluster === "Advanced").reduce((a, s) => a + s.cpi, 0) / students.filter(s => s.cluster === "Advanced").length), color: "hsl(152, 60%, 50%)" },
  { name: "Intermediate", count: students.filter(s => s.cluster === "Intermediate").length, avgCpi: Math.round(students.filter(s => s.cluster === "Intermediate").reduce((a, s) => a + s.cpi, 0) / students.filter(s => s.cluster === "Intermediate").length), color: "hsl(210, 80%, 55%)" },
  { name: "Beginner", count: students.filter(s => s.cluster === "Beginner").length, avgCpi: Math.round(students.filter(s => s.cluster === "Beginner").reduce((a, s) => a + s.cpi, 0) / students.filter(s => s.cluster === "Beginner").length), color: "hsl(38, 92%, 50%)" },
];
